language: go
sudo: false
go:
  - 1.10.x
before_install:
  - go get golang.org/x/lint/golint
  - go get honnef.co/go/tools/cmd/staticcheck
jobs:
  include:
    - script: make all
    - stage: Run Test Coverage
      script: make cover
      after_success: bash <(curl -s https://codecov.io/bash)
    - stage: Build Release
      script:
        - make release
        - echo "Deploying to GitHub releases ..."
      deploy:
        provider: releases
        file:
          - cross/riddler-linux-amd64
          - cross/riddler-linux-amd64.md5
          - cross/riddler-linux-amd64.sha256
        skip_cleanup: true
        on:
          tags: true
        api_key:
          secure: "tZcL5g2y7d7jX1Z+XorS5XNGEd6aJuVaHWFtwxE/6Zp5fLSYhIOwQDWvbXE+HnNAEIifD9B5vfQnh3EwFvwMeHVxQzH/IA83UCqL76ocyv/XR3F7HVR2opBl6vyK9jCGzAD9r5Gqc8+RGQY035y6V+9e1JiIyWyzthrhB1zgeaDdtNK2pkfRuEVx5/3/W6V7cgEjJqieyWiz4HJKV60J2lk/KFU7AlX06vq39v1ixJZB5p3rV4+8bBbhmKD+2oMWox2tQpePX0eKHMFRDHORu0d8ECZ59oKCCBsbnI85ZoGIbq+J6qyjpT1zFIywtFPifKfnoKwNkt5zSMlQuzjN8x1XCbmhOvmGLc/Xdhp4K2k2mhX6uUwxu01f89PyAam1PKGbl87Zd11i2eCRifLkF7jF9NcVwKzaY5cc5B12nlMJkHq7+Uboul2fL0fX8Mt3dkxYEkLmh7yPx1v213FV3wuK7WGpBKpzbT9+NRyQ6764/63C+fDH3mHJVdc2uJCwXp8/DRsSBXbyX3gh2mK9fKv+IKVoQOTUtBIQe3Ex5zVWRG3edL+xlScjjXqfYxj/gKgzLG5p+JnLY6hquTyQBQ5rwXqMUVPAJvzOAhamD8Mpkr+DVBWKEqE4TflFZfqJPLq0vjlcXV8cJtbWpsGzH/s2kRaHhY9Kg/p8jw7N0AE="
